map_columns:
  - name
map_method: random1
input_file: /Users/oleksandrapopovych/PycharmProjects/pseudPy/pseudPy/test_files/plain_user_data.csv
output_to_file: true
pos_type: null
output: /Users/oleksandrapopovych/PycharmProjects/pseudPy/pseudPy/test_files
mapping: true
encrypt_map: true
all_ne: false
seed: 300
patterns: null
